swipe:
  3:
    up:
        command: "pamixer --allow-boost -i 2" # volume inc
    down:
        command: "pamixer --allow-boost -d 2" # volume dec
  4:
    up:
      command: "xrandr --output eDP-1 --brightness $(perl -e \"printf $(xrandr --verbose | grep -m1 Brightness | grep -o '[0-9].*') + 0.1\") " # brightness inc 
    down:
      command: "xrandr --output eDP-1 --brightness $(perl -e \"printf $(xrandr --verbose | grep -m1 Brightness | grep -o '[0-9].*') - 0.1\") " # brightness inc 



threshold:
  swipe: 0.1

interval:
  swipe: 0.1
  pinch: 0.1




