#! /bin/sh

#autostart 
sxhkd &
killall polybar
polybar top &
polybar bottom &
polybar top1 &
polybar bottom1 &
dunst &
picom --experimental-backends &
killall fusuma && fusuma &
fusuma &
redshift -l $LOCATION_LAT:$LOCATION_LON &

#wallpaper
#nitrogen --head=1 --random ~/Pictures/wallpapers/bspwm/fantasy-landscape_darker.jpg --set-auto &
nitrogen --head=0 --random ~/Pictures/wallpapers/bspwm/fantasy-landscape_darker.jpg --set-auto &

# swap CapsLk with esc 
setxkbmap -option caps:swapescape &


# multi monitor
xrandr --output eDP1 --primary --mode 1920x1080 --pos 1280x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --mode 1280x1024 --pos 0x0 --rotate normal --output VIRTUAL1 --off &



bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0 11 12 13 14 15 16 17 18 19 10
bspc monitor HDMI1 -d 21 22 23 24 25 26 27 29 29 20

#config
bspc config border_radius                 8
bspc config border_width                  4
bspc config window_gap                    6

#padding
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

#mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#color
bspc config normal_border_color           "#333333"
bspc config active_border_color           "#888888"
bspc config focused_border_color          "#34be5b"
bspc config presel_feedback_color         "#666666"
bspc config urgent_border_color           "#555555"

#window rules (https://www.reddit.com/r/bspwm/comments/ka34xr/bspc_rule_based_on_net_wm_name/gfe8rb4/)
bspc rule -a discord desktop='9' 
bspc rule -a "*:*:YouTube Music" desktop=0

