#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --random ~/Pictures/wallpapers/bspwm --set-zoom-fill &
polybar example &
dunst &
# multi monitor
xrandr --output eDP1 --primary --mode 1920x1080 --pos 1280x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --mode 1280x1024 --pos 0x0 --rotate normal --output VIRTUAL1 --off &
# swap CapsLk with esc 
setxkbmap -option caps:swapescape &


bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0 11 12 13 14 15 16 17 18 19 10
bspc monitor HDMI1 -d 21 22 23 24 25 26 27 29 29 20

bspc config border_width         5
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^8' follow=off
